apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: dapr-emailprocessorsystem
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      secretKeyRef:
        name: state.redisPassword
        key: state.redisPassword
    - name: actorStateStore
      value: 'true'
auth:
  secretStore: emailprocessorsystem-secrets
scopes:
  - emailfetchingservice
